# Usar la imagen oficial de Apache
FROM httpd:latest

# Copiar los archivos de la página web al directorio raíz de Apache
COPY . /usr/local/apache2/htdocs/

# Exponer el puerto 80 para acceder al servidor
EXPOSE 80
