version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_bd
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Americo2025"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
    driver: local