version: '3.9'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "sqlcmd -U sa -P Your_password123 -Q 'SELECT 1'"]
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 30s
  web:
    build: .
    environment:
      - DEFAULT_CONNECTION=Server=db;Database=E3Db;User=sa;Password=Your_password123;TrustServerCertificate=True;
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    command: ["/bin/sh", "-c", "dotnet ef database update && dotnet e3-csharp.dll"]
